name: Documentation

on:
  pull_request:
  push:
    branches: ['*.x']
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    uses: mortalkiller/filament-package-template/.github/workflows/reusable-docs.yml@ab75c479985ea2281b3a551ef70881b3b7094a51
    with:
      artifact-name: filament-complete-user-profile-docs
      deploy: false
