name: Package standard

on:
  pull_request:
  push:
    branches: ['*.x']
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: standard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  standard:
    uses: mortalkiller/filament-package-template/.github/workflows/reusable-standard-check.yml@6ceb549dd431ccbec57e1fcf67321df2b40b0a92
    with:
      standard-ref: 6ceb549dd431ccbec57e1fcf67321df2b40b0a92
